name: Hello World Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Failure
        run: exit 1  # This will make the job fail intentionally

      - name: Send Notification on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ GitHub Actions job failed in repo: '${{ github.repository }}'.\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.WEBHOOK_URL }}
